name: MkDocs Build Check

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install MkDocs and plugins
        run: |
          pip install mkdocs mkdocs-material

      # Build the site
      - name: Build MkDocs site
        run: |
          mkdocs build --strict

